### ISSUE TITLE
TomoTwin installation issues

### ISSUE THREAD

**Issue by bionanopatterning** [MPI-Dortmund/tomotwin-cryoet#20] opened 2023-05-17 15:02 UTC
Hi there,

First of all, TomoTwin looks super impressive and useful and I look forward to trying it out.

Unfortunately, I'm encountering a couple of issues that I was hoping someone could help me with. My apologies if this is not the right place, or if these issues turn out to be super specific to my setup - I'm using a server PC to which I have limited access in terms of rights, so that may be part of the problem (but it doesn't look like this is the case just yet). I hope that this post can be mutually helpful, but if it turns out that these are indeed probably local problems I'll mark this post solved and see if our sysadmin can help me out instead.

I'm on Debian GNU/Linux 11 with kernel 5.10.0-22-amd64 and eight Nvidia GeForce RTX 3080's. TomoTwin was installed exactly as described here: https://tomotwin-cryoet.readthedocs.io/en/stable/installation.html

**Problem 1**
This one may be normal but just wanted to check: embedding one tomogram (10apix, 1.1 Gb, 1584 x 1125 pixels and 157 slices) takes seven hours when using two GPUs. Is this normal?

Log output:
```

(tomotwin) ...> CUDA_VISIBLE_DEVICES=0,1 tomotwin_embed.py tomogram -m tomotwin_model_p120_052022_loss.pth -v ali_tomo_1_corrected__rec_10A.mrc -b 256 -o out/embed/tomo/ -s 2
Latest version of TomoTwin is installed :-)
reading tomotwin_model_p120_052022_loss.pth
Model config:
{'identifier': 'SiameseNet', 'network_config': {'output_channels': 32, 'dropout': 0.2, 'repeat_layers': 0, 'norm_name': 'GroupNorm', 'norm_kwargs': {'num_groups': 64, 'num_channels': 1024}, 'gem_pooling_p': 0}, 'train_config': {'loss': 'TripletLoss', 'tl_margin': 0.539, 'miner': True, 'miner_margin': 0.734, 'learning_rate': 5.945e-05, 'optimizer': 'Adam', 'weight_decay': 0, 'batchsize': 35, 'patience': 50, 'aug_train_shift_distance': 2}, 'distance': 'COSINE', 'window_size': (37, 37, 37)}
Embeddings have shape: (25731630, 35)
Wrote embeddings to disk to out/embed/tomo/ali_tomo_1_corrected__rec_10A_embeddings.temb
Done.

```

**Problem 2**
After embedding, the generation of the umap crashes right upon starting due to some problem with numba.
```
(tomotwin) ...> tomotwin_tools.py umap -i out/embed/tomo/tomo_embedding.temb -o tomotwin
Traceback (most recent call last):
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/bin/tomotwin_tools.py", line 5, in <module>
    from tomotwin.tools_main import _main_
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/tomotwin/tools_main.py", line 390, in <module>
    from tomotwin.modules.tools.umap import UmapTool
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/tomotwin/modules/tools/umap.py", line 7, in <module>
    import cuml
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/cuml/__init__.py", line 17, in <module>
    from cuml.common.base import Base
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/cuml/common/__init__.py", line 17, in <module>
    from cuml.common.array import CumlArray
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/cuml/common/array.py", line 25, in <module>
    from cudf import DataFrame
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/cudf/utils/gpu_utils.py", line 20, in validate_setup
    from rmm._cuda.gpu import (
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "device_buffer.pyx", line 1, in init rmm._lib.device_buffer
  File "stream.pyx", line 26, in init rmm._cuda.stream
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/scisoft/x86-64/anaconda/2021.05/envs/tomotwin/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

Log output:
```

**Problem 3**
In the napari-tomotwin environment, napari won't launch due to an issue with pyqt (some dependency missing in that environment I guess?)

```
(napari-tomotwin) ...> napari_boxmanager ali_tomo_1_corrected__rec_10A.mrc
Traceback (most recent call last):
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/napari/_qt/__init__.py", line 9, in <module>
    from qtpy import API_NAME, QtCore
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/napari/__main__.py", line 218, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/napari/_event_loop.py", line 2, in <module>
    from ._qt.qt_event_loop import gui_qt, run
  File "/scisoft/x86-64/anaconda/2021.05/envs/napari-tomotwin/lib/python3.10/site-packages/napari/_qt/__init__.py", line 12, in <module>
    raise type(e)(
TypeError: QtBindingsNotFoundError.__init__() takes 1 positional argument but 2 were given

Log output:
```

Any help much appreciated, thanks in advance!

**Comment by thorstenwagner** [comment] 2023-05-18 08:14
Hi!

Thanks for getting in touch!

I will have a look as quick as possible and answer you :-)

Best
Thorsten

17.05.2023 17:02:42 bionanopatterning ***@***.***>:

**Comment by thorstenwagner** [comment] 2023-05-22 07:17
Hi again!

As for problem 1:

Please see X for more details, but the short answer is yes, it very much depends of your GPU and if you have a parallel file system or not.

As for problem 2:

Thanks, I can reproduce it. There is a problem with the installation procedure with the recent numba update. A quick fix is to downgrade numba within your tomotwin environment:
```
mamba install numba==0.56.3
```

Can't reproduce problem 3 so far. Will come back to that issue.

**Comment by thorstenwagner** [comment] 2023-05-22 08:18
For problem 3:

From within the `napari-tomotwin` environment, could you provide the output of 
```conda list```

**Comment by thorstenwagner** [comment] 2023-05-22 09:58
With the installation instructions for TomoTwin 0.4.3 problem 2 should be fixed

**Comment by thorstenwagner** [comment] 2023-05-22 13:27
As for problem 2:

Hi, it looks like that you didn't create the environment `napari-tomotwin` with `conda`. Basically all packages were installed via pypi and many packages from conda-forge etc are missing. Could you run [step 2 (Install napari) ](https://tomotwin-cryoet.readthedocs.io/en/stable/installation.html#install-napari) of the installation instructions again? 

And before  you run

 `pip install napari-boxmanager napari-tomotwin` 

could you check with `which pip` if the pip from your `napari-tomotwin` environment is used? Should look similar to this: 

`/path/to/conda/installation/envs/napari-tomotwin/bin/pip`

**Comment by thorstenwagner** [comment] 2023-07-11 10:57
I assume its solved. Please reopen in case it isnt.

**Closed by thorstenwagner** 2023-07-11 10:57 UTC
Labels: bug
