### ISSUE TITLE
pytorch related warning/errors

### ISSUE THREAD

**Issue by jychoi0616** [MPI-Dortmund/tomotwin-cryoet#51] opened 2023-10-06 11:23 UTC
Hi team,

Thank you for developing tomotwin.

I’ve got a following warning/errors after the third step of embedding my tomogram:

/data/miniconda3/envs/tomotwin/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:347: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
....
Calculate embeddings (1):   6%|\u2588\u2589                            | 56672/889366 [1:18:40<19:13:39, 12.03it/s]Traceback (most recent call last):

(then it stopped with these error messages:)
...
  File "/data/miniconda3/envs/tomotwin/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 360, in rebuild_storage_fd
    storage = cls._new_shared_fd_cpu(fd, size)
RuntimeError: unable to mmap 512 bytes from file <filename not specified>: Cannot allocate memory (12)
.....

/data/miniconda3/envs/tomotwin/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 21 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Do you think you could help in this please?

Thanks a lot,
Joy

**Comment by thorstenwagner** [comment] 2023-10-12 13:10
Hi Joy,

could you try to run `tomotwin_embed.py` with the argument `-d 0` ?

It will be a bit slower, but that would tell me if the new distributed embedding calculation is the problem.

Best,
Thorsten

**Comment by jychoi0616** [comment] 2023-10-12 16:05
Hi Thorsten,

Thank you & hope you had a lovely vacation.
I tried and it's running for without showing errors but just this usual warning:
/data/miniconda3/envs/tomotwin/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:347: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(

Best wishes,
Joy

**Comment by jychoi0616** [comment] 2023-10-13 22:11
Hi Thorsten, 
So it successfully ran, but as you said it took quite a while (> 24 hrs).
Could you suggest how to get around this please?

**Comment by thorstenwagner** [comment] 2023-10-17 12:26
Hm, not sure what the problem is. However, I fixed several related things in 0.6.1.

Could you try the latest version and check if it works with with the `-d` parameter?

Here is how to upgrade tomotwin:
https://tomotwin-cryoet.readthedocs.io/en/stable/installation.html#update-tomotwin-napari

**Comment by jychoi0616** [comment] 2023-10-19 08:33
Hi Thorsten,

Thank you.
It worked with -d parameter both in 0.6.1 and 0.6.01 version. and without -d parameter, 0.6.1 shows runtime error when it reached >90% progress. I guess I could use with the -d parameter.
What does -d parameter do?

**Comment by thorstenwagner** [comment] 2023-12-09 22:21
With -d 1 you get the better parallelism and compiled models.

**Comment by thorstenwagner** [comment] 2023-12-19 09:32
On solution could be to update your nvidia graphics driver. I will close this issue. Reopen if you are still interested.

**Closed by thorstenwagner** 2023-12-19 09:32 UTC

**Comment by jychoi0616** [comment] 2023-12-19 14:35
Thanks a lot!
